/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.EulerBL;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Fabian
 */
public class EulerGUI extends javax.swing.JFrame
{

  /**
   * Creates new form EulerGUI
   */
  public EulerGUI()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    paNorth = new javax.swing.JPanel();
    btCalculate = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    cbProblem1 = new javax.swing.JCheckBox();
    cbProblem9 = new javax.swing.JCheckBox();
    cbProblem20 = new javax.swing.JCheckBox();
    cbProblem24 = new javax.swing.JCheckBox();
    cbRandom = new javax.swing.JCheckBox();
    jScrollPane2 = new javax.swing.JScrollPane();
    taResult = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    paNorth.setLayout(new java.awt.BorderLayout());

    btCalculate.setText("Calculate");
    btCalculate.addActionListener(this::onCalculate);
    paNorth.add(btCalculate, java.awt.BorderLayout.SOUTH);

    jPanel1.setLayout(new java.awt.GridLayout(5, 0));

    cbProblem1.setFont(new java.awt.Font("sansserif", Font.BOLD, 12)); // NOI18N
    cbProblem1.setText("1 - Multiples of 3 and 5");
    jPanel1.add(cbProblem1);

    cbProblem9.setFont(new java.awt.Font("sansserif", Font.BOLD, 12)); // NOI18N
    cbProblem9.setText("9 - Special Pythagorean Triplet");
    jPanel1.add(cbProblem9);

    cbProblem20.setFont(new java.awt.Font("sansserif", Font.BOLD, 12)); // NOI18N
    cbProblem20.setText("20 - Factorial Digit Sum");
    jPanel1.add(cbProblem20);

    cbProblem24.setFont(new java.awt.Font("sansserif", Font.BOLD, 12)); // NOI18N
    cbProblem24.setText("24 - Lexicographic Permutations");
    jPanel1.add(cbProblem24);

    cbRandom.setFont(new java.awt.Font("sansserif", Font.BOLD, 12)); // NOI18N
    cbRandom.setText("?? - Choose one more problem");
    jPanel1.add(cbRandom);

    paNorth.add(jPanel1, java.awt.BorderLayout.CENTER);

    getContentPane().add(paNorth, java.awt.BorderLayout.PAGE_START);

    taResult.setEditable(false);
    taResult.setColumns(20);
    taResult.setRows(5);
    jScrollPane2.setViewportView(taResult);

    getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onCalculate(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCalculate
  {//GEN-HEADEREND:event_onCalculate
    boolean one;
    boolean nine;
    boolean twenty;
    boolean twentyfour;
    boolean random;
    
    taResult.setText("");
    
    one = cbProblem1.isSelected();
    nine = cbProblem9.isSelected();
    twenty = cbProblem20.isSelected();
    twentyfour = cbProblem24.isSelected();
    random = cbRandom.isSelected();
    
    if(one)
    {
      int sum = EulerBL.multy();
      taResult.append("Problem 1 (Multiples of 3 and 5):\n");
      taResult.append(sum + "\n");
      taResult.append("-----------------------------\n");
    }
    
    if(nine)
    {
      int result = EulerBL.triplet();
      taResult.append("Problem 9 (Pythagorean Triplet):\n");
      taResult.append(result + "\n");
      taResult.append("-----------------------------\n");
    }
    
    if(twenty)
    {
      int result = EulerBL.factorial();
      taResult.append("Problem 20 (Factorial Digit Number):\n");
      taResult.append(result + "\n");
      taResult.append("-----------------------------\n");
    }
    
    if(twentyfour)
    {
      String result = EulerBL.permutations();
      taResult.append("Problem 24 (Lexicographic Permutation):\n");
      taResult.append(result + "\n");
      taResult.append("-----------------------------\n");
    }
    
    if(random)
    {
      String result = EulerBL.powerDigitSum();
      taResult.append("Problem 16 (Power digit sum):\n");
      taResult.append(result + "\n");
      taResult.append("-----------------------------\n");
    }
    
  }//GEN-LAST:event_onCalculate

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args)
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(EulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() ->
            new EulerGUI().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btCalculate;
  private javax.swing.JCheckBox cbProblem1;
  private javax.swing.JCheckBox cbProblem20;
  private javax.swing.JCheckBox cbProblem24;
  private javax.swing.JCheckBox cbProblem9;
  private javax.swing.JCheckBox cbRandom;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JPanel paNorth;
  private javax.swing.JTextArea taResult;
  // End of variables declaration//GEN-END:variables
}
